name: demoappliaction
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  firebase_auth:
  firebase_core:
  firebase_crashlytics: ^2.1.1
  firebase_analytics: ^9.3.5
  firebase_messaging: ^13.0.2

  firebase_messaging_platform_interface: ^4.1.4
  firebase_crashlytics_platform_interface: ^3.2.16
  firebase_dynamic_links: 3.0.0
  firebase_messaging_web: ^3.1.4
  flutter_local_notifications: ^9.7.0
  stacked: ^3.0.0
  # flutter_inappwebview:
  font_awesome_flutter: ^10.2.1
  google_fonts: ^3.0.1
  percent_indicator: ^4.2.2
  qlevar_router: ^1.6.4
  get_it: ^7.2.0
  formz: ^0.4.0
  shared_preferences: ^2.0.15
  connectivity_plus: ^2.1.0
  device_info: ^2.0.3
  device_info_plus: 4.0.0
  encrypt: ^5.0.1
  platform_device_id:
  signaturefingerprint: ^1.0.0
  flutter_screenutil: 5.0.0+2
  flutter_custom_dialog: ^1.2.0
  after_init: ^0.1.2
  web_ffi: ^0.7.2
  mask_text_input_formatter: ^2.3.0
  currency_text_input_formatter: ^2.1.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  web_smooth_scroll: ^1.0.0
  flutter_bloc: ^7.3.3
  equatable: ^2.0.0
  local_auth: ^1.1.7
  expandable_bottom_sheet: ^1.1.1+1
  image_picker: ^0.8.4+1
  image: ^3.1.3
  image_cropper: ^1.5.0
  adaptive_action_sheet: ^2.0.1
  flutter_markdown:
  rxdart: ^0.27.2
  fluttertoast: 8.1.2
  path_provider: ^2.0.4
  intl: ^0.17.0
  circular_countdown: 2.1.0
  step_progress_indicator: ^1.0.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^3.2.0
  qr_code_tools: ^0.0.7
  flutter_barcode_scanner:
  scan: ^1.6.0
  async: ^2.6.1
  page_transition: ^2.0.4
  #automated flavor configuration
  flutter_flavor: ^3.0.3
  flutter_secure_storage: ^6.0.0
  pull_to_refresh: ^2.0.0
  #Skeleton Loading

  loading: ^1.0.2
  cached_network_image: ^3.2.0
  easy_sidemenu: ^0.4.0
  pin_code_fields: ^7.2.0
  flutter_countdown_timer: ^4.1.0
  slide_to_act: ^2.0.1
  skeleton_loader: ^2.0.0+4
  smooth_page_indicator:
  carousel_slider: 4.0.0
  roundcheckbox: ^2.0.3+1
  js: ^0.6.4
  #pdf creator
  pdf:
  share: ^2.0.4
  mockito: ^5.0.0
  let_log: ^1.1.4
  custom_radio_grouped_button: ^2.1.1
  flutter_cache_manager: ^3.3.0
  flutter_multi_formatter: ^2.5.1
  currency_textfield: ^2.0.0
  flutter_udid: ^2.0.0
  exif: ^2.0.0
  #device_preview: ^1.0.0
  camera: 0.10.4
  camera_android: 0.10.6+2
  permission_handler:
  flutter_staggered_grid_view: ^0.6.2
  url_launcher: ^6.1.2
  google_maps_flutter:
  # google_maps_flutter: ^2.1.5
  webview_flutter: ^4.2.1
  uuid: ^3.0.6
  video_player:
  image_picker_for_web: ^2.1.10
  beamer: 1.5.6
  flutter_easyloading: ^3.0.5
  universal_html: 1.2.4
  otp_text_field: ^1.1.1
  #hydrated_bloc: 7.1.051
  carousel_indicator: ^1.0.6
  screenshot: ^1.3.0
  image_gallery_saver: ^1.7.1
  # image_downloader_web: 2.0.0
  share_files_and_screenshot_widgets: ^1.0.6
  badges: ^2.0.1
  #profile preference
  kosher_dart: ^2.0.13
  hijri: ^3.0.0
  lunar_calendar: ^1.0.1
  collection: ^1.15.0
  package_info_plus: 1.4.0
  client_information: ^2.0.4
  flutter_share: ^2.0.0
  passcode_screen: ^2.0.1
  huawei_map: ^6.11.0
  google_maps: ^6.3.0
  contacts_service: ^0.6.3
  # flutter accordion
  accordion: ^2.6.0
  # webview_flutter: ^4.2.1
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - lib/Asset/logo/svg/logo-black.svg
    - lib/Asset/logo/png/logo-color.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
